version: "3.1"
services:
    web:
        image: nginx:latest
        ports:
            - "3000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        # restart: always
        environment:
            MARIADB_ROOT_PASSWORD: pass
            MARIADB_DATABASE: main
            MARIADB_USER: user
            MARIADB_PASSWORD: pass
        volumes:
            - ./databases:/var/lib/mysql
        ports:
            - 3307:3306
    adminer:
        image: adminer
        # restart: always
        ports:
            - 8080:8080
